const http = require('http');
const fs = require('fs');
const path = require('path');

// Test configuration
const API_BASE_URL = 'http://localhost:3000/api';
const TEST_RESULTS_FILE = path.join(__dirname, 'appointment_workflow_test_results.json');

// Test data - These will be populated by the seed script
let testPatientId = '507f1f77bcf86cd799439011'; // Default fallback
let testDoctorId = '507f1f77bcf86cd799439012'; // Default fallback
const testHospitalId = 'HOSP_TEST_001'; // Matches seed data

// Utility function to make HTTP requests
function makeRequest(method, url, data = null) {
  return new Promise((resolve, reject) => {
    const urlObj = new URL(url);
    const options = {
      hostname: urlObj.hostname,
      port: urlObj.port,
      path: urlObj.pathname + urlObj.search,
      method: method,
      headers: {
        'Content-Type': 'application/json',
      }
    };

    const req = http.request(options, (res) => {
      let responseData = '';
      
      res.on('data', (chunk) => {
        responseData += chunk;
      });
      
      res.on('end', () => {
        try {
          const parsedData = responseData ? JSON.parse(responseData) : {};
          resolve({
            statusCode: res.statusCode,
            data: parsedData,
            headers: res.headers
          });
        } catch (error) {
          resolve({
            statusCode: res.statusCode,
            data: responseData,
            headers: res.headers
          });
        }
      });
    });

    req.on('error', (error) => {
      reject(error);
    });

    if (data) {
      req.write(JSON.stringify(data));
    }

    req.end();
  });
}

// Test results tracking
const testResults = {
  timestamp: new Date().toISOString(),
  tests: [],
  summary: {
    total: 0,
    passed: 0,
    failed: 0
  }
};

function logTest(testName, status, details) {
  const result = {
    testName,
    status,
    details,
    timestamp: new Date().toISOString()
  };
  
  testResults.tests.push(result);
  testResults.summary.total++;
  
  if (status === 'PASS') {
    testResults.summary.passed++;
    console.log(`✅ ${testName}: PASSED`);
  } else {
    testResults.summary.failed++;
    console.log(`❌ ${testName}: FAILED`);
    console.log(`   Details: ${JSON.stringify(details, null, 2)}`);
  }

  // Write results to file after each test
  fs.writeFileSync(TEST_RESULTS_FILE, JSON.stringify(testResults, null, 2));
}

// Get test data IDs from database
async function getTestDataIds() {
  console.log('\n🔍 Fetching test data IDs from database...');
  
  try {
    // Get test patient ID
    const patientResponse = await makeRequest('GET', `${API_BASE_URL.replace('/api', '')}/api/patients`);
    if (patientResponse.statusCode === 200 && patientResponse.data.length > 0) {
      const testPatient = patientResponse.data.find(p => p.uhid === 'TEST_PATIENT_001');
      if (testPatient) {
        testPatientId = testPatient._id;
        console.log(`   Patient ID: ${testPatientId}`);
      }
    }

    // Get test doctor ID  
    const doctorResponse = await makeRequest('GET', `${API_BASE_URL}/doctors/hospital/${testHospitalId}`);
    if (doctorResponse.statusCode === 200 && doctorResponse.data.length > 0) {
      const testDoctor = doctorResponse.data.find(d => d.doctorId === 'DOC_TEST_001');
      if (testDoctor) {
        testDoctorId = testDoctor._id;
        console.log(`   Doctor ID: ${testDoctorId}`);
      }
    }

    console.log(`   Hospital ID: ${testHospitalId}`);
    return true;
  } catch (error) {
    console.log(`   ⚠️  Using fallback IDs due to error: ${error.message}`);
    return false;
  }
}

// Test functions
async function testPatientAppointmentBooking() {
  console.log('\n📋 Testing Patient Appointment Booking...');
  
  const appointmentData = {
    // Match frontend data structure exactly - no appointmentId (auto-generated by backend)
    patientId: testPatientId,
    patientName: 'John Doe',
    doctorId: testDoctorId,
    doctorName: 'Dr. Smith',
    hospitalId: testHospitalId,
    hospitalName: 'Apollo Hospital',
    appointmentDate: '15/2/2024', // Frontend format (DD/MM/YYYY)
    appointmentTime: '10:00 AM',
    reason: 'Regular checkup',
    consultationFee: 500,
    status: 'pending' // This should work with HospitalAppointment model
  };

  try {
    // Test successful appointment creation
    const response = await makeRequest('POST', `${API_BASE_URL}/appointments`, appointmentData);
    
    if (response.statusCode === 201 || response.statusCode === 200) {
      const appointmentId = response.data.appointmentId || response.data.data?.appointmentId;
      logTest('Patient Appointment Booking - Success Case', 'PASS', {
        statusCode: response.statusCode,
        appointmentId: appointmentId
      });
      return appointmentId;
    } else {
      logTest('Patient Appointment Booking - Success Case', 'FAIL', {
        statusCode: response.statusCode,
        response: response.data
      });
      return null;
    }
  } catch (error) {
    logTest('Patient Appointment Booking - Success Case', 'FAIL', {
      error: error.message
    });
    return null;
  }
}

async function testPatientAppointmentBookingValidation() {
  console.log('\n🔍 Testing Patient Appointment Booking Validation...');
  
  const invalidData = {
    appointmentId: `APT_INVALID_${Date.now()}`,
    patientName: 'Jane Doe',
    // Missing required fields intentionally
  };

  try {
    const response = await makeRequest('POST', `${API_BASE_URL}/appointments`, invalidData);
    
    if (response.statusCode === 400) {
      logTest('Patient Appointment Booking - Validation', 'PASS', {
        statusCode: response.statusCode,
        message: response.data.message
      });
    } else {
      logTest('Patient Appointment Booking - Validation', 'FAIL', {
        statusCode: response.statusCode,
        expectedStatus: 400,
        response: response.data
      });
    }
  } catch (error) {
    logTest('Patient Appointment Booking - Validation', 'FAIL', {
      error: error.message
    });
  }
}

async function testDoctorAppointmentRetrieval() {
  console.log('\n🩺 Testing Doctor Appointment Retrieval...');
  
  try {
    const response = await makeRequest('GET', `${API_BASE_URL}/appointments/doctor/${testDoctorId}`);
    
    if (response.statusCode === 200 && Array.isArray(response.data)) {
      logTest('Doctor Appointment Retrieval', 'PASS', {
        statusCode: response.statusCode,
        appointmentCount: response.data.length,
        firstAppointment: response.data[0] || 'No appointments found'
      });
      return response.data;
    } else {
      logTest('Doctor Appointment Retrieval', 'FAIL', {
        statusCode: response.statusCode,
        response: response.data
      });
      return [];
    }
  } catch (error) {
    logTest('Doctor Appointment Retrieval', 'FAIL', {
      error: error.message
    });
    return [];
  }
}

async function testAppointmentStatusUpdate(appointmentId) {
  console.log('\n📝 Testing Appointment Status Update...');
  
  if (!appointmentId) {
    logTest('Appointment Status Update - No Appointment ID', 'FAIL', {
      reason: 'No appointment ID provided from previous test'
    });
    return;
  }

  try {
    // Test approval
    const approvalResponse = await makeRequest('PUT', `${API_BASE_URL}/appointments/${appointmentId}/status`, {
      status: 'approved'
    });
    
    if (approvalResponse.statusCode === 200) {
      logTest('Appointment Status Update - Approval', 'PASS', {
        statusCode: approvalResponse.statusCode,
        appointmentId: appointmentId,
        newStatus: 'approved'
      });
    } else {
      logTest('Appointment Status Update - Approval', 'FAIL', {
        statusCode: approvalResponse.statusCode,
        response: approvalResponse.data
      });
    }

    // Test rejection
    const rejectionResponse = await makeRequest('PUT', `${API_BASE_URL}/appointments/${appointmentId}/status`, {
      status: 'rejected'
    });
    
    if (rejectionResponse.statusCode === 200) {
      logTest('Appointment Status Update - Rejection', 'PASS', {
        statusCode: rejectionResponse.statusCode,
        appointmentId: appointmentId,
        newStatus: 'rejected'
      });
    } else {
      logTest('Appointment Status Update - Rejection', 'FAIL', {
        statusCode: rejectionResponse.statusCode,
        response: rejectionResponse.data
      });
    }

    // Test invalid status
    const invalidStatusResponse = await makeRequest('PUT', `${API_BASE_URL}/appointments/${appointmentId}/status`, {
      status: 'invalid_status'
    });
    
    if (invalidStatusResponse.statusCode === 400) {
      logTest('Appointment Status Update - Invalid Status', 'PASS', {
        statusCode: invalidStatusResponse.statusCode,
        message: invalidStatusResponse.data.message || invalidStatusResponse.data.error
      });
    } else {
      logTest('Appointment Status Update - Invalid Status', 'FAIL', {
        statusCode: invalidStatusResponse.statusCode,
        expectedStatus: 400,
        response: invalidStatusResponse.data
      });
    }

  } catch (error) {
    logTest('Appointment Status Update - Error', 'FAIL', {
      error: error.message
    });
  }
}

async function testPatientAppointmentHistory() {
  console.log('\n📜 Testing Patient Appointment History...');
  
  try {
    const response = await makeRequest('GET', `${API_BASE_URL}/appointments/patient/${testPatientId}`);
    
    if (response.statusCode === 200 && Array.isArray(response.data)) {
      logTest('Patient Appointment History', 'PASS', {
        statusCode: response.statusCode,
        appointmentCount: response.data.length,
        appointments: response.data.map(apt => ({
          id: apt.appointmentId,
          status: apt.status,
          date: apt.appointmentDate
        }))
      });
    } else {
      logTest('Patient Appointment History', 'FAIL', {
        statusCode: response.statusCode,
        response: response.data
      });
    }
  } catch (error) {
    logTest('Patient Appointment History', 'FAIL', {
      error: error.message
    });
  }
}

async function testServerConnectivity() {
  console.log('\n🔗 Testing Server Connectivity...');
  
  try {
    const response = await makeRequest('GET', `${API_BASE_URL}/health`);
    
    if (response.statusCode === 200 || response.statusCode === 404) {
      logTest('Server Connectivity', 'PASS', {
        statusCode: response.statusCode,
        message: 'Server is reachable'
      });
      return true;
    } else {
      logTest('Server Connectivity', 'FAIL', {
        statusCode: response.statusCode,
        response: response.data
      });
      return false;
    }
  } catch (error) {
    logTest('Server Connectivity', 'FAIL', {
      error: error.message,
      message: 'Server might not be running on port 3000'
    });
    return false;
  }
}

// Main test execution
async function runComprehensiveTests() {
  console.log('🚀 Starting Comprehensive Appointment Workflow Tests');
  console.log('================================================');
  console.log(`📊 Results will be saved to: ${TEST_RESULTS_FILE}`);
  
  // Test server connectivity first
  const serverConnected = await testServerConnectivity();
  
  if (!serverConnected) {
    console.log('\n❌ Server connectivity failed. Please ensure backend server is running on port 3000');
    return;
  }

  // Get test data IDs from database
  await getTestDataIds();

  // Run the test sequence
  const appointmentId = await testPatientAppointmentBooking();
  await testPatientAppointmentBookingValidation();
  await testDoctorAppointmentRetrieval();
  await testAppointmentStatusUpdate(appointmentId);
  await testPatientAppointmentHistory();

  // Final summary
  console.log('\n📊 Test Summary');
  console.log('===============');
  console.log(`Total Tests: ${testResults.summary.total}`);
  console.log(`Passed: ${testResults.summary.passed}`);
  console.log(`Failed: ${testResults.summary.failed}`);
  console.log(`Success Rate: ${((testResults.summary.passed / testResults.summary.total) * 100).toFixed(1)}%`);
  console.log(`\n📄 Detailed results saved to: ${TEST_RESULTS_FILE}`);

  if (testResults.summary.failed > 0) {
    console.log('\n❌ Some tests failed. Check the detailed results file for more information.');
    process.exit(1);
  } else {
    console.log('\n✅ All tests passed! The appointment workflow is working correctly.');
    process.exit(0);
  }
}

// Handle uncaught exceptions
process.on('uncaughtException', (error) => {
  console.error('❌ Uncaught Exception:', error);
  logTest('Uncaught Exception', 'FAIL', { error: error.message });
  process.exit(1);
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('❌ Unhandled Rejection at:', promise, 'reason:', reason);
  logTest('Unhandled Rejection', 'FAIL', { reason: reason });
  process.exit(1);
});

// Run the tests
if (require.main === module) {
  runComprehensiveTests();
}

module.exports = {
  runComprehensiveTests,
  makeRequest,
  testResults
};