const mongoose = require('mongoose');

const patientSchema = new mongoose.Schema({
  // Authentication credentials
  username: {
    type: String,
    required: false, // Will be auto-generated after registration
    unique: true,
    sparse: true, // Allows null values temporarily
    trim: true
  },
  password: {
    type: String,
    required: true
  },
  
  // Universal Health Identity (UHID) - Auto-generated
  uhid: {
    type: String,
    unique: true,
    trim: true
  },
  
  // Personal Information
  firstName: {
    type: String,
    required: true,
    trim: true
  },
  lastName: {
    type: String,
    required: true,
    trim: true
  },
  fullName: {
    type: String,
    trim: true
  },
  aadhaarNumber: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    validate: {
      validator: function(v) {
        return /^\d{12}$/.test(v);
      },
      message: 'Aadhaar number must be exactly 12 digits'
    }
  },
  email: {
    type: String,
    unique: true,
    sparse: true, // Allows multiple null/undefined values since email is optional
    trim: true,
    default: undefined // Explicitly set default to undefined instead of null
  },
  photo: {
    type: String, // Base64 encoded image or file path
    required: false
  },
  phone: {
    type: String,
    required: true,
    trim: true
  },
  dateOfBirth: {
    type: Date,
    required: true
  },
  gender: {
    type: String,
    enum: ['male', 'female', 'other'],
    required: true
  },
  bloodGroup: {
    type: String,
    enum: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    required: true
  },
  
  // Address Information
  address: {
    street: { type: String, required: true },
    city: { type: String, required: true },
    state: { type: String, required: true },
    zipCode: { type: String, required: true },
    country: { type: String, default: 'India' }
  },
  
  // Emergency Contact
  emergencyContact: {
    name: { type: String, required: true },
    relationship: { type: String, required: true },
    phone: { type: String, required: true }
  },
  
  // Medical Information
  medicalHistory: [{
    condition: String,
    diagnosedDate: Date,
    notes: String
  }],
  allergies: [String],
  currentMedications: [{
    name: String,
    dosage: String,
    frequency: String
  }],
  
  // Migrant Worker Specific
  isMigrant: {
    type: Boolean,
    default: false
  },
  migrantDetails: {
    currentState: String,
    currentCity: String,
    registeredHospital: String,
    migrationDate: Date,
    workLocation: String,
    employerName: String,
    workPermitNumber: String
  },
  homeState: {
    type: String,
    required: true
  },
  
  // Digital Health Card
  digitalCard: {
    qrCode: String, // QR code data for quick access
    cardNumber: String, // Same as UHID
    issueDate: { type: Date, default: Date.now },
    isActive: { type: Boolean, default: true }
  },
  
  // System fields
  isActive: {
    type: Boolean,
    default: true
  },
  registrationDate: {
    type: Date,
    default: Date.now
  },
  lastLogin: {
    type: Date
  }
});

// Pre-save middleware to set fullName, username and digital card
patientSchema.pre('save', async function(next) {
  try {
    // Generate fullName
    if (this.firstName && this.lastName) {
      this.fullName = `${this.firstName} ${this.lastName}`;
    }
    
    // Set username to be same as UHID (UHID should be generated by UHI service before saving)
    if (!this.username && this.uhid) {
      this.username = this.uhid;
      console.log('Set username to UHID:', this.username);
    }
    
    // Set digital card details
    if (this.uhid) {
      if (!this.digitalCard) {
        this.digitalCard = {};
      }
      
      if (!this.digitalCard.cardNumber) {
        this.digitalCard.cardNumber = this.uhid;
      }
      
      if (!this.digitalCard.qrCode) {
        this.digitalCard.qrCode = generateQRCodeData(this);
      }
      
      if (!this.digitalCard.issueDate) {
        this.digitalCard.issueDate = new Date();
      }
      
      if (this.digitalCard.isActive === undefined) {
        this.digitalCard.isActive = true;
      }
      
      console.log('Generated digital card:', {
        cardNumber: this.digitalCard.cardNumber,
        issueDate: this.digitalCard.issueDate,
        isActive: this.digitalCard.isActive
      });
    }
    
    next();
  } catch (error) {
    console.error('Error in pre-save middleware:', error);
    next(error);
  }
});

// Function to generate comprehensive QR code data
function generateQRCodeData(patientData) {
  return JSON.stringify({
    uhid: patientData.uhid,
    name: patientData.fullName,
    address: {
      street: patientData.address?.street || '',
      city: patientData.address?.city || '',
      state: patientData.address?.state || '',
      zipCode: patientData.address?.zipCode || '',
      country: patientData.address?.country || 'India'
    },
    homeState: patientData.homeState,
    bloodGroup: patientData.bloodGroup,
    emergencyContact: {
      name: patientData.emergencyContact?.name || '',
      phone: patientData.emergencyContact?.phone || ''
    },
    type: 'DHRMS_PATIENT_CARD',
    version: '2.0',
    timestamp: new Date().toISOString(),
    verificationURL: `https://dhrms.gov.in/verify/${patientData.uhid}`
  });
}

module.exports = mongoose.model('Patient', patientSchema);
